In [26]:
import random
from pathlib import Path

import numpy as np
import polars as pl

In [3]:
train = pl.read_csv(
    "../data/train.csv",
    null_values={"latitude": "None", "longitude": "None"},
    infer_schema_length=10_0000,
)
train

shape: (28_564, 13)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ primary_la ┆ secondary_ ┆ type ┆ filename   ┆ … ┆ scientific ┆ common_na ┆ author    ┆ license   │
│ bel        ┆ labels     ┆ ---  ┆ ---        ┆   ┆ _name      ┆ me        ┆ ---       ┆ ---       │
│ ---        ┆ ---        ┆ str  ┆ str        ┆   ┆ ---        ┆ ---       ┆ str       ┆ str       │
│ str        ┆ str        ┆      ┆            ┆   ┆ str        ┆ str       ┆           ┆           │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 1139490    ┆ ['']       ┆ [''] ┆ 1139490/CS ┆ … ┆ Ragoniella ┆ Ragoniell ┆ Fabio A.  ┆ cc-by-nc- │
│            ┆            ┆      ┆ A36385.ogg ┆   ┆ pulchella  ┆ a         ┆ Sarria-S  ┆ sa 4.0    │
│            ┆            ┆      ┆            ┆   ┆            ┆ pulchella ┆           ┆           │
│ 1139490    ┆ ['']       ┆ [''] ┆ 1139490/CS ┆ … ┆ Ragoniella ┆ Ragoniell ┆ Fabio A.  ┆ cc-by-nc- │
│            ┆            ┆      ┆ A36389.ogg ┆   ┆ pulchella  ┆ a         ┆ Sarria-S  ┆ sa 4.0    │
│            ┆            ┆      ┆            ┆   ┆            ┆ pulchella ┆           ┆           │
│ 1192948    ┆ ['']       ┆ [''] ┆ 1192948/CS ┆ … ┆ Oxyprora   ┆ Oxyprora  ┆ Fabio A.  ┆ cc-by-nc- │
│            ┆            ┆      ┆ A36358.ogg ┆   ┆ surinamens ┆ surinamen ┆ Sarria-S  ┆ sa 4.0    │
│            ┆            ┆      ┆            ┆   ┆ is         ┆ sis       ┆           ┆           │
│ 1192948    ┆ ['']       ┆ [''] ┆ 1192948/CS ┆ … ┆ Oxyprora   ┆ Oxyprora  ┆ Fabio A.  ┆ cc-by-nc- │
│            ┆            ┆      ┆ A36366.ogg ┆   ┆ surinamens ┆ surinamen ┆ Sarria-S  ┆ sa 4.0    │
│            ┆            ┆      ┆            ┆   ┆ is         ┆ sis       ┆           ┆           │
│ 1192948    ┆ ['']       ┆ [''] ┆ 1192948/CS ┆ … ┆ Oxyprora   ┆ Oxyprora  ┆ Fabio A.  ┆ cc-by-nc- │
│            ┆            ┆      ┆ A36373.ogg ┆   ┆ surinamens ┆ surinamen ┆ Sarria-S  ┆ sa 4.0    │
│            ┆            ┆      ┆            ┆   ┆ is         ┆ sis       ┆           ┆           │
│ …          ┆ …          ┆ …    ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ ywcpar     ┆ ['']       ┆ [''] ┆ ywcpar/iNa ┆ … ┆ Amazona    ┆ Yellow-cr ┆ Yennifer  ┆ cc-by-nc  │
│            ┆            ┆      ┆ t77392.ogg ┆   ┆ ochrocepha ┆ owned     ┆ Alfaro    ┆ 4.0       │
│            ┆            ┆      ┆            ┆   ┆ la         ┆ Parrot    ┆           ┆           │
│ ywcpar     ┆ ['']       ┆ [''] ┆ ywcpar/iNa ┆ … ┆ Amazona    ┆ Yellow-cr ┆ Evan      ┆ cc-by-nc- │
│            ┆            ┆      ┆ t78624.ogg ┆   ┆ ochrocepha ┆ owned     ┆ Centanni  ┆ sa 4.0    │
│            ┆            ┆      ┆            ┆   ┆ la         ┆ Parrot    ┆           ┆           │
│ ywcpar     ┆ ['']       ┆ [''] ┆ ywcpar/iNa ┆ … ┆ Amazona    ┆ Yellow-cr ┆ Henrry    ┆ cc-by 4.0 │
│            ┆            ┆      ┆ t789234.og ┆   ┆ ochrocepha ┆ owned     ┆           ┆           │
│            ┆            ┆      ┆ g          ┆   ┆ la         ┆ Parrot    ┆           ┆           │
│ ywcpar     ┆ ['']       ┆ [''] ┆ ywcpar/iNa ┆ … ┆ Amazona    ┆ Yellow-cr ┆ Alejandro ┆ cc-by-nc  │
│            ┆            ┆      ┆ t819873.og ┆   ┆ ochrocepha ┆ owned     ┆ Luy       ┆ 4.0       │
│            ┆            ┆      ┆ g          ┆   ┆ la         ┆ Parrot    ┆           ┆           │
│ ywcpar     ┆ ['']       ┆ [''] ┆ ywcpar/iNa ┆ … ┆ Amazona    ┆ Yellow-cr ┆ Kalvin    ┆ cc-0 4.0  │
│            ┆            ┆      ┆ t922688.og ┆   ┆ ochrocepha ┆ owned     ┆ Chan      ┆           │
│            ┆            ┆      ┆ g          ┆   ┆ la         ┆ Parrot    ┆           ┆           │
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [4]:
labels = train["primary_label"].unique().sort().to_list()
labels

['1139490',
 '1192948',
 '1194042',
 '126247',
 '1346504',
 '134933',
 '135045',
 '1462711',
 '1462737',
 '1564122',
 '21038',
 '21116',
 '21211',
 '22333',
 '22973',
 '22976',
 '24272',
 '24292',
 '24322',
 '41663',
 '41778',
 '41970',
 '42007',
 '42087',
 '42113',
 '46010',
 '47067',
 '476537',
 '476538',
 '48124',
 '50186',
 '517119',
 '523060',
 '528041',
 '52884',
 '548639',
 '555086',
 '555142',
 '566513',
 '64862',
 '65336',
 '65344',
 '65349',
 '65373',
 '65419',
 '65448',
 '65547',
 '65962',
 '66016',
 '66531',
 '66578',
 '66893',
 '67082',
 '67252',
 '714022',
 '715170',
 '787625',
 '81930',
 '868458',
 '963335',
 'amakin1',
 'amekes',
 'ampkin1',
 'anhing',
 'babwar',
 'bafibi1',
 'banana',
 'baymac',
 'bbwduc',
 'bicwre1',
 'bkcdon',
 'bkmtou1',
 'blbgra1',
 'blbwre1',
 'blcant4',
 'blchaw1',
 'blcjay1',
 'blctit1',
 'blhpar1',
 'blkvul',
 'bobfly1',
 'bobher1',
 'brtpar1',
 'bubcur1',
 'bubwre1',
 'bucmot3',
 'bugtan',
 'butsal1',
 'cargra1',
 'cattyr',
 'chbant1',
 'chfma

In [5]:
label_to_idx = {label: i for i, label in enumerate(labels)}
label_to_idx

{'1139490': 0,
 '1192948': 1,
 '1194042': 2,
 '126247': 3,
 '1346504': 4,
 '134933': 5,
 '135045': 6,
 '1462711': 7,
 '1462737': 8,
 '1564122': 9,
 '21038': 10,
 '21116': 11,
 '21211': 12,
 '22333': 13,
 '22973': 14,
 '22976': 15,
 '24272': 16,
 '24292': 17,
 '24322': 18,
 '41663': 19,
 '41778': 20,
 '41970': 21,
 '42007': 22,
 '42087': 23,
 '42113': 24,
 '46010': 25,
 '47067': 26,
 '476537': 27,
 '476538': 28,
 '48124': 29,
 '50186': 30,
 '517119': 31,
 '523060': 32,
 '528041': 33,
 '52884': 34,
 '548639': 35,
 '555086': 36,
 '555142': 37,
 '566513': 38,
 '64862': 39,
 '65336': 40,
 '65344': 41,
 '65349': 42,
 '65373': 43,
 '65419': 44,
 '65448': 45,
 '65547': 46,
 '65962': 47,
 '66016': 48,
 '66531': 49,
 '66578': 50,
 '66893': 51,
 '67082': 52,
 '67252': 53,
 '714022': 54,
 '715170': 55,
 '787625': 56,
 '81930': 57,
 '868458': 58,
 '963335': 59,
 'amakin1': 60,
 'amekes': 61,
 'ampkin1': 62,
 'anhing': 63,
 'babwar': 64,
 'bafibi1': 65,
 'banana': 66,
 'baymac': 67,
 'bbwduc': 68,
 

In [6]:
filename = train["filename"][0]
primary_label = train["primary_label"][0]
filename, primary_label

('1139490/CSA36385.ogg', '1139490')

In [7]:
base_name = Path(filename).stem
base_name

'CSA36385'

In [8]:
sorted((Path("../data/train_melspectrograms/") / base_name).glob("*.npy"))

[PosixPath('../data/train_melspectrograms/CSA36385/0000.npy'),
 PosixPath('../data/train_melspectrograms/CSA36385/0001.npy'),
 PosixPath('../data/train_melspectrograms/CSA36385/0002.npy'),
 PosixPath('../data/train_melspectrograms/CSA36385/0003.npy'),
 PosixPath('../data/train_melspectrograms/CSA36385/0004.npy'),
 PosixPath('../data/train_melspectrograms/CSA36385/0005.npy'),
 PosixPath('../data/train_melspectrograms/CSA36385/0006.npy'),
 PosixPath('../data/train_melspectrograms/CSA36385/0007.npy'),
 PosixPath('../data/train_melspectrograms/CSA36385/0008.npy'),
 PosixPath('../data/train_melspectrograms/CSA36385/0009.npy'),
 PosixPath('../data/train_melspectrograms/CSA36385/0010.npy'),
 PosixPath('../data/train_melspectrograms/CSA36385/0011.npy'),
 PosixPath('../data/train_melspectrograms/CSA36385/0012.npy'),
 PosixPath('../data/train_melspectrograms/CSA36385/0013.npy'),
 PosixPath('../data/train_melspectrograms/CSA36385/0014.npy'),
 PosixPath('../data/train_melspectrograms/CSA36385/0015

In [21]:
np.identity(len(labels))[[label_to_idx[label] for label in train["primary_label"].to_list()]]

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(28564, 206))

In [31]:
from typing import Literal

from torch.utils.data import Dataset


class BirdCLEFDataset(Dataset):
    def __init__(
        self,
        mode: Literal["train", "val", "test"],
        df: pl.DataFrame,
        mel_spec_path: Path,
        transform=None,
    ):
        self.mode = mode
        self.df = df

        # Create a dictionary mapping each filename to its slices
        self.file_to_slices: dict[str, list[Path]] = {}
        self.file_to_label: dict[str, int] = {}

        # Get unique class labels and create a mapping
        unique_labels = df["primary_label"].unique().sort().to_list()
        self.label_to_idx = {label: i for i, label in enumerate(unique_labels)}
        self.labels = np.identity(len(unique_labels), dtype=np.float32)[
            [self.label_to_idx[label] for label in df["primary_label"].to_list()]
        ]

        self.filenames = df["filename"].to_list()
        primary_labels = df["primary_label"].to_list()
        # Find all available slices for each filename
        for filename, primary_label in zip(self.filenames, primary_labels):
            # Get all slice paths for this filename (excluding file extension)
            base_name = Path(filename).stem
            slices = sorted((mel_spec_path / base_name).glob("*.npy"))

            self.file_to_slices[filename] = slices
            self.file_to_label[filename] = self.label_to_idx[primary_label]

        self.transform = transform

    def __len__(self):
        return len(self.filenames)

    def __getitem__(self, idx):
        filename = self.filenames[idx]

        slice_path = random.choice(self.file_to_slices[filename])

        mel_spec = np.load(slice_path)

        label = self.labels[idx]

        if self.transform:
            mel_spec = self.transform(mel_spec)
        return mel_spec, label

In [32]:
dataset = BirdCLEFDataset(mode="train", df=train, mel_spec_path=Path("../data/train_melspectrograms/"))

In [33]:
dataset.__getitem__(0)

(array([[0.5497307 , 0.719552  , 0.65621495, ..., 0.6433851 , 0.5748559 ,
         0.72283006],
        [0.49159327, 0.7097593 , 0.60964584, ..., 0.7861729 , 0.7863866 ,
         0.82524604],
        [0.47966257, 0.69782853, 0.5977151 , ..., 0.7742421 , 0.7744559 ,
         0.8133153 ],
        ...,
        [0.19566816, 0.18619163, 0.20057067, ..., 0.11939979, 0.19319436,
         0.16368262],
        [0.1946166 , 0.18357417, 0.1910464 , ..., 0.16406652, 0.17945935,
         0.13293996],
        [0.17399047, 0.1515616 , 0.17885607, ..., 0.12126432, 0.18485747,
         0.12615621]], shape=(128, 313), dtype=float32),
 array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 